import SwiftUI

/// **La hoja impresa de un corte de caja.**
///
/// Es el papel que acompaña al sobre: qué movimientos junta el corte, cuánto
/// suma, si una segunda persona lo contó y le salió lo mismo, las dos firmas y,
/// al pie, la ficha recortable que se entrega en la ventanilla del banco.
///
/// Sigue el diseño «1 · Corte de caja» de *PDFs Faltantes* con tres cambios, y
/// los tres son por lo mismo — **la hoja solo imprime lo que el corte guarda**:
///
/// - **Sin tabla de billetes y monedas.** El corte no guarda denominaciones;
///   una tabla de «3 × $500» sacada de la nada sería una cifra firmada que
///   nadie contó. En su lugar va el doble conteo, que sí existe: lo registrado,
///   lo que contó el asistente a ciegas y la diferencia.
/// - **Sin el importe en letra** en la ficha. En la app no hay nada que pase
///   números a letra, y escribirlo a mano en el diseño («cuatro mil ciento
///   veinte pesos») no lo hace existir.
/// - **La ficha con lo que hay**: si el corte ya se depositó, la cuenta, la
///   fecha y la referencia del depósito; si no, rayas en blanco para llenarlas
///   en el banco.
///
/// Solo depende de `Tamio/Support`, `Models`, `Data` y `ViewModels`, que son las
/// carpetas que compilan los dos targets: la misma hoja sale en el iPhone y en
/// el Mac. Nada de UIKit ni AppKit — las rúbricas llegan como
/// `ImagenPlataforma` a través de `FirmaEnLinea`.
///
/// Solo LEE el corte. No marca nada, no mueve dinero.
struct CorteHojaPDF: View {
    let corte: Corte
    var iglesia: ConfiguracionIglesia = ConfiguracionIglesiaViewModel.compartido.config
    var firmas: FirmasLocales = .compartidas

    /// **El nombre del archivo, uno solo para el iPhone y el Mac.** La fecha
    /// del corte y no su título: ordena bien en una carpeta y no cambia con el
    /// idioma. Lleva el principio del id porque un domingo puede tener dos
    /// cortes —el de la mañana y el de la tarde— y el segundo PDF pisaría al
    /// primero en la carpeta temporal.
    static func nombreArchivo(_ corte: Corte) -> String {
        let fecha = corte.registro.fecha.trimmingCharacters(in: .whitespaces)
        let id = String(corte.id.prefix(6))
        return fecha.isEmpty ? "Corte-\(id)" : "Corte-\(fecha)-\(id)"
    }

    // MARK: - Estilo

    /// Los grises del diseño, que son los secundarios de Apple sobre blanco.
    /// Se escriben como opacidades del negro y no como `.secondary` porque la
    /// hoja se pinta SIEMPRE en claro, también en un Mac en modo oscuro.
    private let tinta2 = Color.black.opacity(0.6)
    private let filete = Color.black.opacity(0.29)
    private let fileteSuave = Color.black.opacity(0.18)
    /// El verde de marca, solo en cifras. `Paleta.brand` y no el `#157A4B`
    /// del diseño: es el mismo verde que imprimen el estado financiero y la
    /// constancia (`#136E44` en claro), y dos verdes de marca en la misma
    /// carpeta de papeles se notan. La hoja fuerza el modo claro, así que
    /// nunca sale el verde aclarado del modo oscuro.
    private let verde = Paleta.brand

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            membrete
            Rectangle().fill(filete).frame(height: 0.75).padding(.vertical, 14)
            cifras
            HStack(alignment: .top, spacing: 18) {
                dobleConteo.frame(width: 168, alignment: .topLeading)
                movimientos.frame(maxWidth: .infinity, alignment: .topLeading)
            }
            .padding(.top, 16)
            firmasCorte.padding(.top, 24)
            Spacer(minLength: 20)
            lineaDeCorte
            ficha
            VStack(alignment: .leading, spacing: 3) {
                PieInstitucionalPDF(iglesia: iglesia)
                Text(L.t("Generado por Tamio", "Generated by Tamio"))
                    .font(.system(size: 8.5)).foregroundStyle(Color.black.opacity(0.4))
            }
            .padding(.top, 10)
        }
        .foregroundStyle(.black)
        .padding(48)
        // El ancho de la página, explícito: es el contrato de todas las hojas.
        // Sin él cada `Text` se mide a una línea y lo largo sale cortado en "…".
        .frame(width: PDFExport.anchoCarta, alignment: .leading)
        .background(.white)
        .environment(\.colorScheme, .light)   // el papel siempre en claro
    }

    // MARK: - Membrete

    /// **Centrado, como el acta y las cartas**, y no con el logo a la izquierda
    /// como lo pinta el diseño: los documentos que se firman encabezan
    /// centrados, y un corte se firma. `.multilineTextAlignment` va en el
    /// contenedor por lo que explica `CartaHojaPDF`: un nombre de iglesia que
    /// envuelve saldría en bandera a la izquierda.
    private var membrete: some View {
        VStack(alignment: .center, spacing: 4) {
            LogoMembrete(alto: 52)
            Text(L.t("Corte de caja", "Cash count"))
                .font(.system(.title3, design: .serif).bold())
            if !iglesia.nombre.isEmpty {
                Text(iglesia.nombre).font(.caption).foregroundStyle(tinta2)
            }
            Text(subtitulo).font(.caption.weight(.semibold)).foregroundStyle(tinta2)
            Text(estadoLegible).font(.caption2).foregroundStyle(tinta2)
        }
        .frame(maxWidth: .infinity)
        .multilineTextAlignment(.center)
        .fixedSize(horizontal: false, vertical: true)
    }

    /// "Corte #48 · 11 sep 2026". El título es el que el corte ya lleva en la
    /// app; la fecha, la del registro (la de ir al banco).
    private var subtitulo: String {
        let fecha = corte.registro.fecha.isEmpty ? "" : Fechas.diaLegible(corte.registro.fecha)
        return [corte.titulo, fecha].filter { !$0.isEmpty }.joined(separator: " · ")
    }

    /// El diseño pone "Cerrado 6:10 p. m.", y esa hora no se guarda. Lo que sí
    /// hay es si el dinero ya está en el banco y a qué periodo suma.
    private var estadoLegible: String {
        let estado = corte.estado == .depositado
            ? L.t("Depositado", "Deposited")
            : L.t("Sin depositar", "Not deposited")
        let periodo = Fechas.periodoLegible(corte.registro.periodo)
        return periodo.isEmpty ? estado
            : L.t("\(estado) · Periodo \(periodo)", "\(estado) · Period \(periodo)")
    }

    // MARK: - Las cuatro cifras

    /// **Cheques y no transferencias.** El diseño separa efectivo y
    /// transferencias, pero lo que agrupa un corte es lo que hay que LLEVAR al
    /// banco: efectivo y cheques, que van en la misma ficha (`listoParaDepositar`).
    private var cifras: some View {
        HStack(spacing: 0) {
            celdaCifra(L.t("EFECTIVO", "CASH"), Money.fmt(corte.efectivoSeleccionado))
            celdaCifra(L.t("CHEQUES", "CHECKS"), Money.fmt(corte.chequesMonto))
            celdaCifra(L.t("TOTAL DEL CORTE", "CUT TOTAL"), Money.fmt(corte.montoTotal),
                       color: verde, peso: .bold)
            celdaCifra(L.t("DIFERENCIA", "DIFFERENCE"),
                       corte.diferenciaConteo.map(firmado) ?? "—",
                       color: colorDiferencia(corte.diferenciaConteo ?? 0), ultima: true)
        }
        .overlay(RoundedRectangle(cornerRadius: 10).stroke(Color.black.opacity(0.3), lineWidth: 0.75))
    }

    /// El filete entre celdas va en un `overlay` de cada celda y no como una
    /// vista más del `HStack`: un `Rectangle` suelto pide todo el alto que le
    /// propongan, y `ImageRenderer` mide la hoja con alto libre.
    private func celdaCifra(_ rotulo: String, _ valor: String,
                            color: Color = .black, peso: Font.Weight = .semibold,
                            ultima: Bool = false) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(rotulo).font(.system(size: 9.5, weight: .bold)).tracking(0.5)
                .foregroundStyle(tinta2)
            // Una línea y sin `minimumScaleFactor`: dentro de `ImageRenderer`
            // aplica el factor mínimo siempre. Las celdas miden ~129 pt, que
            // caben siete cifras a 15 pt.
            Text(valor).font(.system(size: 15, weight: peso)).monospacedDigit()
                .foregroundStyle(color).lineLimit(1)
        }
        .padding(.horizontal, 12).padding(.vertical, 9)
        .frame(maxWidth: .infinity, alignment: .leading)
        .overlay(alignment: .trailing) {
            if !ultima { Rectangle().fill(Color.black.opacity(0.2)).frame(width: 0.5) }
        }
    }

    /// "+$20.00" / "−$20.00" / "$0.00". Con el menos tipográfico (U+2212), como
    /// `Money.firmado`: en una diferencia el signo es lo que se lee primero.
    private func firmado(_ c: Centavos) -> String {
        c == 0 ? Money.fmt(0) : (c > 0 ? "+" : "\u{2212}") + Money.fmt(abs(c))
    }

    // MARK: - El doble conteo (en lugar de los billetes y monedas)

    /// **Lo registrado contra lo que contó otra persona**, que es el único
    /// control de la app que compara el dinero físico con lo apuntado.
    ///
    /// Si no hay segundo conteo se DICE, en vez de poner $0.00: un cero en
    /// "Contado por el asistente" se lee como "contó y no había nada".
    private var dobleConteo: some View {
        VStack(alignment: .leading, spacing: 0) {
            Text(L.t("Doble conteo", "Second count"))
                .font(.system(size: 12.5, weight: .semibold)).padding(.bottom, 4)
            Rectangle().fill(filete).frame(height: 0.75)

            // Casi siempre es el mismo número que el total de la tabla de al
            // lado. Si el corte trae algo que no es efectivo ni cheque, el
            // asistente contó solo lo que va al banco, y el rótulo lo dice para
            // que dos "Total registrado" distintos no convivan en la hoja.
            filaConteo(totalRegistrado == corte.montoTotal
                       ? L.t("Total registrado", "Total recorded")
                       : L.t("Efectivo y cheques registrados", "Cash and checks recorded"),
                       Money.fmt(corte.montoTotal))

            if let contado = corte.segundaConteo {
                filaConteo(L.t("Contado por el asistente", "Counted by the assistant"),
                           Money.fmt(contado))
                if let d = corte.diferenciaConteo {
                    filaConteo(L.t("Diferencia", "Difference"), firmado(d), fuerte: true,
                               color: colorDiferencia(d))
                    Text(d == 0
                         ? L.t("Cuadra.", "It adds up.")
                         : (d > 0 ? L.t("Sobra dinero respecto a lo registrado.",
                                        "There is more money than recorded.")
                                  : L.t("Falta dinero respecto a lo registrado.",
                                        "There is less money than recorded.")))
                        .font(.system(size: 9.5)).foregroundStyle(tinta2)
                        .fixedSize(horizontal: false, vertical: true)
                        .padding(.top, 4)
                }
            } else {
                Text(sinConteo)
                    .font(.system(size: 10)).foregroundStyle(tinta2)
                    .fixedSize(horizontal: false, vertical: true)
                    .padding(.top, 6)
            }
        }
    }

    /// Por qué no hay cifra del asistente. Son tres casos distintos y no se
    /// confunden: revisar el registro NO es contar el dinero (ver
    /// `ModoSegundaFirma`).
    private var sinConteo: String {
        if corte.tieneSegundaFirma, corte.modoSegundaFirma == .revision {
            return L.t("El asistente revisó el registro; no volvió a contar el dinero.",
                       "The assistant checked the record; the money was not recounted.")
        }
        if corte.dobleFirmaPedida {
            return L.t("Sin segundo conteo todavía.", "No second count yet.")
        }
        return L.t("Este corte no pidió segundo conteo.", "This cut did not ask for a second count.")
    }

    /// **Una diferencia nunca va en verde**: el verde se lee como "bien", y
    /// un faltante de $1,351.75 pintado así parecía una buena noticia. En
    /// rojo si falta dinero, en negro si cuadra o sobra (sobrar tampoco es
    /// "bien": también hay que explicarlo).
    private func colorDiferencia(_ d: Centavos) -> Color {
        d < 0 ? Paleta.negativo : .black
    }

    private func filaConteo(_ rotulo: String, _ valor: String, fuerte: Bool = false,
                            color: Color? = nil) -> some View {
        VStack(alignment: .leading, spacing: 1) {
            Text(rotulo).font(.system(size: 9.5, weight: .semibold)).foregroundStyle(tinta2)
                .fixedSize(horizontal: false, vertical: true)
            Text(valor).font(.system(size: 12, weight: fuerte ? .bold : .semibold))
                .monospacedDigit().foregroundStyle(color ?? verde).lineLimit(1)
        }
        .padding(.vertical, 5)
        .frame(maxWidth: .infinity, alignment: .leading)
        .overlay(alignment: .bottom) { Rectangle().fill(fileteSuave).frame(height: 0.5) }
    }

    // MARK: - Los movimientos

    private var movimientos: some View {
        VStack(alignment: .leading, spacing: 0) {
            Text(L.t("Movimientos que agrupa", "Transactions in this cut"))
                .font(.system(size: 12.5, weight: .semibold)).padding(.bottom, 4)

            filaMovimiento(L.t("FOLIO", "FOLIO"), L.t("Concepto", "Description"),
                           L.t("Método", "Method"), L.t("Importe", "Amount"), cabecera: true)
                .overlay(alignment: .bottom) { Rectangle().fill(filete).frame(height: 0.75) }

            if corte.movimientos.isEmpty {
                Text(L.t("Este corte no agrupa ningún movimiento.",
                         "This cut has no transactions."))
                    .font(.system(size: 11)).foregroundStyle(tinta2).padding(.vertical, 6)
            }
            ForEach(corte.movimientos) { m in
                filaMovimiento(m.folio, m.titular, metodo(m), Money.fmt(m.monto))
                    .overlay(alignment: .bottom) { Rectangle().fill(fileteSuave).frame(height: 0.5) }
            }

            // La suma de las filas de arriba, tal cual: es lo que se coteja
            // contra el talonario.
            HStack {
                Text(L.t("Total registrado", "Total recorded"))
                Spacer()
                Text(Money.fmt(totalRegistrado)).monospacedDigit().lineLimit(1)
            }
            .font(.system(size: 11, weight: .semibold))
            .padding(.vertical, 5)

            Text(nota)
                .font(.system(size: 9.5)).foregroundStyle(tinta2).lineSpacing(2)
                .fixedSize(horizontal: false, vertical: true)
                .padding(.top, 4)
        }
    }

    /// La suma de todas las filas. Se calcula aquí y no con `Corte.suma`, que
    /// vive en `TamioMac/TablaDepositos.swift` y el iPhone no compila.
    private var totalRegistrado: Centavos { corte.movimientos.reduce(0) { $0 + $1.monto } }

    /// La nota del diseño hablaba de transferencias que ya estaban en el
    /// banco. Aquí lo que hay que explicar es qué va en la ficha, y si algo del
    /// corte NO va en ella (un método que no es efectivo ni cheque), decirlo:
    /// si no, "Total registrado" y "Total del corte" no coincidirían sin
    /// explicación.
    private var nota: String {
        let fuera = totalRegistrado - corte.montoTotal
        let base = L.t("La diferencia compara lo que contó el asistente con lo registrado en Tamio. El efectivo y los cheques van juntos en la misma ficha.",
                       "The difference compares what the assistant counted with what Tamio recorded. Cash and checks go on the same slip.")
        guard fuera != 0 else { return base }
        return base + " " + L.t("\(Money.fmt(fuera)) de otros métodos no van en la ficha.",
                                "\(Money.fmt(fuera)) in other methods are not on the slip.")
    }

    /// El número del cheque manda, como en el detalle del corte: es lo que el
    /// banco pide en la ficha.
    ///
    /// **El método en la lengua de la hoja, no el texto guardado.** Se pintaba
    /// `m.metodo` tal cual: en una hoja en inglés salía «Efectivo» al lado de
    /// «Check 8823». Se reconoce la clave con `Catalogos.clave(deMetodo:)` y se
    /// escribe con las mismas etiquetas de `Catalogos.metodos`; lo que no se
    /// reconoce —un método que inventó la iglesia— se deja como lo escribió.
    private func metodo(_ m: Movimiento) -> String {
        if let n = m.numeroCheque { return L.t("Cheque \(n)", "Check \(n)") }
        switch m.claveMetodo {
        case .efectivo?:      return L.t("Efectivo", "Cash")
        case .cheque?:        return L.t("Cheque", "Check")
        case .transferencia?: return L.t("Transferencia", "Transfer")
        case .tarjeta?:       return L.t("Tarjeta", "Card")
        case .domiciliado?:   return L.t("Domiciliado", "Direct debit")
        case nil:             return m.metodo
        }
    }

    private func filaMovimiento(_ folio: String, _ concepto: String, _ metodo: String,
                                _ importe: String, cabecera: Bool = false) -> some View {
        HStack(alignment: .firstTextBaseline, spacing: 6) {
            Text(folio).foregroundStyle(tinta2).lineLimit(1)
                .frame(width: 40, alignment: .leading)
            Text(concepto).lineSpacing(1)
                .fixedSize(horizontal: false, vertical: true)
                .frame(maxWidth: .infinity, alignment: .leading)
            Text(metodo).foregroundStyle(tinta2).lineLimit(1)
                .frame(width: 66, alignment: .leading)
            // 76 pt y no los 66 del diseño: `$12,345.00` a 11 pt no cabía, y
            // una cifra no puede partirse en dos renglones.
            Text(importe).monospacedDigit().lineLimit(1)
                .foregroundStyle(cabecera ? tinta2 : verde)
                .frame(width: 76, alignment: .trailing)
        }
        .font(cabecera ? .system(size: 9.5, weight: .semibold) : .system(size: 11))
        .padding(.vertical, 4)
    }

    // MARK: - Firmas

    /// **Dos firmas, no las tres del diseño**: quien armó el corte y quien lo
    /// contó por segunda vez. El diseño pone "Contó", "Verificó" y "Tesorero";
    /// el corte guarda a dos personas, y una tercera raya no tendría nombre.
    ///
    /// La rúbrica del tesorero se estampa como en `FirmasPDF`: solo si quien
    /// firma es el tesorero de Ajustes y la guardó en este aparato. La del
    /// asistente nunca: su firma en la app es un nombre y una fecha, no un
    /// trazo, así que su raya queda para firmar a mano.
    private var firmasCorte: some View {
        HStack(alignment: .top, spacing: 32) {
            FirmaEnLinea(nombre: tesorero,
                         cargo: Catalogos.Cargos.cargo(iglesia.tesoreroCargo, o: .tesorero),
                         imagen: tesorero == iglesia.tesoreroNombre ? firmas.imagen(.tesorero) : nil)
                .frame(maxWidth: .infinity)
            FirmaEnLinea(nombre: corte.tieneSegundaFirma ? (corte.segundaFirma ?? "") : "",
                         cargo: cargoAsistente,
                         fechaFirma: corte.tieneSegundaFirma
                            ? corte.segundaFirmaEn.map { String($0.prefix(10)) } : nil)
                .frame(maxWidth: .infinity)
        }
    }

    /// Quien armó el corte; si no consta, el tesorero de Ajustes.
    private var tesorero: String {
        let r = corte.registradoPor.trimmingCharacters(in: .whitespaces)
        return r.isEmpty ? iglesia.tesoreroNombre : r
    }

    /// El rol con el que firmó y QUÉ hizo: contar el dinero y revisar el
    /// registro no son lo mismo, y la hoja no los puede confundir.
    private var cargoAsistente: String {
        let rol = (corte.segundaFirmaRol?.isEmpty == false ? corte.segundaFirmaRol : nil)
            ?? L.t("Asistente", "Assistant")
        switch corte.modoSegundaFirma {
        case .conteo?:   return L.t("\(rol) · Contó", "\(rol) · Counted")
        case .revision?: return L.t("\(rol) · Revisó el registro", "\(rol) · Checked the record")
        case nil:        return rol
        }
    }

    // MARK: - La ficha recortable

    private var lineaDeCorte: some View {
        HStack(spacing: 8) {
            Image(systemName: "scissors")
            LineaPunteada()
            Text(L.t("Recortar y entregar en ventanilla", "Cut and hand to the teller"))
                .fixedSize()
            LineaPunteada()
        }
        .font(.system(size: 9.5))
        .foregroundStyle(Color.black.opacity(0.5))
        .padding(.top, 14).padding(.bottom, 10)
    }

    /// **Solo lo que existe.** Con el depósito registrado, sus datos; sin él,
    /// la raya en blanco para escribirlo en el banco. Nada de importe en letra:
    /// la app no tiene cómo escribirlo (ver el comentario del tipo).
    private var ficha: some View {
        HStack(alignment: .top, spacing: 16) {
            VStack(alignment: .leading, spacing: 6) {
                HStack(alignment: .firstTextBaseline, spacing: 8) {
                    Text(L.t("Ficha de depósito", "Deposit slip"))
                        .font(.system(size: 12.5, weight: .bold))
                    Text(corte.titulo).font(.system(size: 10)).foregroundStyle(tinta2)
                }
                Grid(alignment: .leading, horizontalSpacing: 8, verticalSpacing: 4) {
                    filaFicha(L.t("Cuenta", "Account"), texto: cuenta)
                    filaFicha(L.t("Titular", "Account holder"),
                              texto: iglesia.nombre.isEmpty ? nil : iglesia.nombre)
                    GridRow {
                        Text(L.t("Importe", "Amount")).foregroundStyle(tinta2)
                        VStack(alignment: .leading, spacing: 1) {
                            Text(Money.fmt(corte.montoTotal))
                                .fontWeight(.bold).monospacedDigit().lineLimit(1)
                            if corte.chequesCount > 0 {
                                Text(L.t("\(Money.fmt(corte.efectivoSeleccionado)) en efectivo y \(corte.chequesCount) cheque\(corte.chequesCount == 1 ? "" : "s") por \(Money.fmt(corte.chequesMonto))",
                                         "\(Money.fmt(corte.efectivoSeleccionado)) in cash and \(corte.chequesCount) check\(corte.chequesCount == 1 ? "" : "s") for \(Money.fmt(corte.chequesMonto))"))
                                    .font(.system(size: 9.5)).foregroundStyle(tinta2)
                                    .fixedSize(horizontal: false, vertical: true)
                            }
                        }
                    }
                    filaFicha(L.t("Fecha de depósito", "Deposit date"),
                              texto: corte.deposito.map { Fechas.diaLegible($0.fecha) })
                    filaFicha(L.t("Referencia", "Reference"),
                              texto: corte.deposito.flatMap { $0.referencia.isEmpty ? nil : $0.referencia })
                }
                .font(.system(size: 10.5))
            }
            .frame(maxWidth: .infinity, alignment: .leading)

            // El sello lo pone el banco: la app solo deja el hueco. Va en el
            // `background` de los datos y no como hermano con alto infinito:
            // con `fixedSize` + `maxHeight: .infinity` el renderizador medía
            // la fila al alto del sello y la raya de «Referencia» quedaba
            // pegada al borde de abajo (visto por el lead en el PDF). Así el
            // alto lo mandan los datos, y el sello se estira hasta ellos.
        }
        .padding(.trailing, 120 + 16)
        .background(alignment: .trailing) {
            Text(L.t("Sello del banco", "Bank stamp"))
                .font(.system(size: 9.5)).foregroundStyle(Color.black.opacity(0.5))
                .multilineTextAlignment(.center)
                .frame(width: 120)
                .frame(maxHeight: .infinity)
                .overlay(RoundedRectangle(cornerRadius: 8)
                    .stroke(Color.black.opacity(0.35), style: StrokeStyle(lineWidth: 1, dash: [3, 3])))
        }
        .padding(.horizontal, 14).padding(.top, 11).padding(.bottom, 14)
        .overlay(RoundedRectangle(cornerRadius: 10).stroke(Color.black.opacity(0.35), lineWidth: 0.75))
    }

    /// La cuenta del depósito si ya se hizo (es la que de verdad recibió el
    /// dinero); si no, la que el corte tiene asignada. "Sin asignar" no es una
    /// cuenta: deja la raya.
    private var cuenta: String? {
        if let d = corte.deposito, !d.cuenta.isEmpty { return d.cuenta }
        return corte.sinCuenta ? nil : corte.registro.cuenta
    }

    /// Una fila de la ficha: el dato, o una raya para escribirlo a mano.
    /// Devuelve `GridRow` con su tipo a la vista y no un `some View` a secas,
    /// para que `Grid` la reconozca como fila y alinee las columnas.
    private func filaFicha(_ rotulo: String, texto: String?) -> GridRow<some View> {
        GridRow {
            Text(rotulo).foregroundStyle(tinta2)
            if let texto {
                Text(texto).fixedSize(horizontal: false, vertical: true)
            } else {
                Rectangle().fill(Color.black.opacity(0.4))
                    .frame(width: 160, height: 0.75)
                    .frame(height: 13, alignment: .bottom)
            }
        }
    }
}

/// La raya discontinua de "recortar aquí".
private struct LineaPunteada: View {
    var body: some View {
        GeometryReader { g in
            Path { p in
                p.move(to: CGPoint(x: 0, y: g.size.height / 2))
                p.addLine(to: CGPoint(x: g.size.width, y: g.size.height / 2))
            }
            .stroke(Color.black.opacity(0.4), style: StrokeStyle(lineWidth: 1, dash: [3, 3]))
        }
        .frame(height: 1)
    }
}
