import SwiftUI

/// Tramo de tiempo de un reporte de aportes.
enum PeriodoReporte: String, CaseIterable, Identifiable {
    case semana, mes, anio, rango
    var id: String { rawValue }

    var etiqueta: String {
        switch self {
        case .semana: return L.t("Semana", "Week")
        case .mes:    return L.t("Mes", "Month")
        case .anio:   return L.t("Año", "Year")
        case .rango:  return L.t("Rango", "Range")
        }
    }

    /// Intervalo que cubre, contando hacia atrás desde hoy.
    func intervalo(desde: Date, hasta: Date) -> ClosedRange<Date> {
        let cal = Calendar.current
        let hoy = Date()
        switch self {
        case .semana:
            let inicio = cal.date(byAdding: .day, value: -7, to: hoy) ?? hoy
            return inicio...hoy
        case .mes:
            let inicio = cal.date(byAdding: .month, value: -1, to: hoy) ?? hoy
            return inicio...hoy
        case .anio:
            let inicio = cal.date(from: DateComponents(year: cal.component(.year, from: hoy),
                                                       month: 1, day: 1)) ?? hoy
            return inicio...hoy
        case .rango:
            return desde <= hasta ? desde...hasta : hasta...desde
        }
    }
}

// MARK: - Reporte de aportes (informativo)

/// Lo que dio una persona en un tramo de tiempo. Es informativo —"esto diste,
/// gracias"— así que **no lleva firmas**: no es un comprobante fiscal y no
/// debería parecerlo.
struct ReporteAportesHojaPDF: View {
    let aportante: Aportante
    let aportes: [Aporte]
    let periodoLegible: String
    let iglesia: ConfiguracionIglesia

    private var total: Centavos { aportes.reduce(0) { $0 + $1.monto } }

    var body: some View {
        VStack(alignment: .leading, spacing: 22) {
            VStack(alignment: .leading, spacing: 4) {
                Text(L.t("Reporte de aportes", "Giving report"))
                    .font(.system(.title, design: .serif).weight(.bold))
                Text(periodoLegible).font(.headline).foregroundStyle(.secondary)
                if !iglesia.membrete.isEmpty {
                    Text(iglesia.membrete).font(.subheadline).foregroundStyle(.secondary)
                }
            }

            Divider()

            VStack(alignment: .leading, spacing: 3) {
                Text(aportante.nombre).font(.headline)
                if !aportante.idFiscal.isEmpty {
                    Text(L.t("ID fiscal: \(aportante.idFiscal)", "Tax ID: \(aportante.idFiscal)"))
                        .font(.caption).foregroundStyle(.secondary)
                }
            }

            if aportes.isEmpty {
                Text(L.t("Sin aportes registrados en este periodo.",
                         "No gifts recorded in this period."))
                    .font(.subheadline).foregroundStyle(.secondary)
            } else {
                tabla
            }

            HStack {
                Text(L.t("Total del periodo", "Period total")).font(.body.weight(.semibold))
                Spacer()
                Text(Money.fmt(total))
                    .font(.title3.weight(.semibold)).monospacedDigit()
                    .foregroundStyle(Paleta.brand)
            }
            .padding(16)
            .overlay(RoundedRectangle(cornerRadius: 12).stroke(.secondary.opacity(0.3)))

            PieInstitucionalPDF(iglesia: iglesia)
            Text(L.t("Generado por Tamio", "Generated by Tamio"))
                .font(.caption2).foregroundStyle(.tertiary)
        }
        .padding(40)
        .frame(width: PDFExport.anchoCarta, alignment: .leading)
        .background(.white)
        .environment(\.colorScheme, .light)
    }

    private var tabla: some View {
        VStack(spacing: 0) {
            HStack {
                Text(L.t("FECHA", "DATE")).frame(width: 120, alignment: .leading)
                Text(L.t("CONCEPTO", "CONCEPT")).frame(maxWidth: .infinity, alignment: .leading)
                Text(L.t("MONTO", "AMOUNT")).frame(width: 120, alignment: .trailing)
            }
            .font(.caption.weight(.semibold)).foregroundStyle(.secondary)
            .padding(.vertical, 8)
            Divider()
            ForEach(aportes) { ap in
                HStack {
                    Text(Fechas.corta(ap.fecha)).frame(width: 120, alignment: .leading)
                    Text(ap.concepto).frame(maxWidth: .infinity, alignment: .leading)
                    Text(Money.fmt(ap.monto)).frame(width: 120, alignment: .trailing)
                }
                .font(.subheadline).monospacedDigit()
                .padding(.vertical, 7)
                if ap.id != aportes.last?.id { Divider() }
            }
        }
    }
}

// MARK: - Constancia anual (fiscal)

/// Comprobante de lo aportado en un año. A diferencia del reporte, este sí
/// lleva identificación fiscal de la iglesia y firmas: es el documento que el
/// aportante puede presentar para deducir.
struct ConstanciaHojaPDF: View {
    let aportante: Aportante
    let aportes: [Aporte]
    let anio: Int
    let iglesia: ConfiguracionIglesia

    private var total: Centavos { aportes.reduce(0) { $0 + $1.monto } }

    /// Suma por concepto: es el desglose que suele pedirse, más útil que
    /// cincuenta renglones sueltos.
    private var porConcepto: [(concepto: String, monto: Centavos)] {
        Dictionary(grouping: aportes, by: \.concepto)
            .map { ($0.key, $0.value.reduce(0) { $0 + $1.monto }) }
            .sorted { $0.monto > $1.monto }
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 22) {
            VStack(alignment: .leading, spacing: 4) {
                if !iglesia.nombre.isEmpty {
                    Text(iglesia.nombre)
                        .font(.system(.title2, design: .serif).weight(.bold))
                }
                if !iglesia.ubicacionLegible.isEmpty {
                    Text(iglesia.ubicacionLegible).font(.subheadline).foregroundStyle(.secondary)
                }
                if !iglesia.idFiscal.isEmpty {
                    Text(L.t("ID fiscal: \(iglesia.idFiscal)", "Tax ID: \(iglesia.idFiscal)"))
                        .font(.caption).foregroundStyle(.secondary)
                }
            }

            Divider()

            Text(L.t("Constancia de aportaciones \(String(anio))",
                     "\(String(anio)) giving statement"))
                .font(.system(.title3, design: .serif).weight(.bold))

            VStack(alignment: .leading, spacing: 3) {
                Text(aportante.nombre).font(.headline)
                if !aportante.idFiscal.isEmpty {
                    Text(L.t("ID fiscal: \(aportante.idFiscal)", "Tax ID: \(aportante.idFiscal)"))
                        .font(.caption).foregroundStyle(.secondary)
                }
                if !aportante.direccion.isEmpty {
                    Text(aportante.direccion).font(.caption).foregroundStyle(.secondary)
                }
            }

            Text(L.t("Se hace constar que la persona arriba señalada realizó durante el año \(String(anio)) las aportaciones voluntarias que se detallan a continuación.",
                     "This certifies that the person named above made the following voluntary contributions during \(String(anio))."))
                .font(.subheadline)

            VStack(spacing: 0) {
                ForEach(Array(porConcepto.enumerated()), id: \.offset) { i, fila in
                    HStack {
                        Text(fila.concepto).frame(maxWidth: .infinity, alignment: .leading)
                        Text(Money.fmt(fila.monto)).frame(width: 140, alignment: .trailing)
                    }
                    .font(.subheadline).monospacedDigit()
                    .padding(.vertical, 8)
                    if i < porConcepto.count - 1 { Divider() }
                }
            }

            HStack {
                Text(L.t("Total aportado en \(String(anio))", "Total given in \(String(anio))"))
                    .font(.body.weight(.semibold))
                Spacer()
                Text(Money.fmt(total))
                    .font(.title3.weight(.semibold)).monospacedDigit()
                    .foregroundStyle(Paleta.brand)
            }
            .padding(16)
            .overlay(RoundedRectangle(cornerRadius: 12).stroke(.secondary.opacity(0.3)))

            FirmasPDF(iglesia: iglesia)
            PieInstitucionalPDF(iglesia: iglesia)
        }
        .padding(40)
        .frame(width: PDFExport.anchoCarta, alignment: .leading)
        .background(.white)
        .environment(\.colorScheme, .light)
    }
}
