import SwiftUI

/// Página imprimible del "Estado financiero". Blanco y negro con verde de marca
/// solo en las cifras, según la ley de color. Es lo que se renderiza al PDF y lo
/// que se ve en la vista previa. Ancho fijo tamaño carta (lo envuelve PDFExport).
struct ReporteHojaPDF: View {
    let e: EstadoFinanciero
    let periodo: String

    var body: some View {
        VStack(alignment: .leading, spacing: 22) {
            // Membrete
            VStack(alignment: .leading, spacing: 4) {
                Text(L.t("Estado financiero", "Financial statement"))
                    .font(.system(.title, design: .serif).weight(.bold))
                Text(periodo).font(.headline).foregroundStyle(.secondary)
                Text("Iglesia Getsemaní · Monterrey, N.L.").font(.subheadline).foregroundStyle(.secondary)
            }

            Divider()

            // Resumen del mes
            VStack(spacing: 0) {
                filaResumen(L.t("Ingresos del mes", "Income this month"), e.ingresosMes, Paleta.brand)
                Divider()
                filaResumen(L.t("Gastos del mes", "Expenses this month"), e.gastosMes, Paleta.negativo)
                Divider()
                filaResumen(L.t("Balance neto", "Net balance"), e.balanceNeto, .primary, negrita: true)
            }
            .padding(16)
            .overlay(RoundedRectangle(cornerRadius: 12).stroke(.secondary.opacity(0.3)))

            // Tabla mensual
            Text(L.t("Resumen mensual", "Monthly summary")).font(.headline)
            VStack(spacing: 0) {
                HStack {
                    Text(L.t("MES", "MONTH")).frame(maxWidth: .infinity, alignment: .leading)
                    Text(L.t("INGRESOS", "INCOME")).frame(width: 110, alignment: .trailing)
                    Text(L.t("GASTOS", "EXPENSES")).frame(width: 110, alignment: .trailing)
                    Text(L.t("BALANCE", "BALANCE")).frame(width: 110, alignment: .trailing)
                }
                .font(.caption.weight(.semibold)).foregroundStyle(.secondary)
                .padding(.vertical, 8)
                Divider()
                ForEach(e.mensual) { f in
                    HStack {
                        Text(f.mes).frame(maxWidth: .infinity, alignment: .leading)
                        Text(Money.fmt(f.ingresos)).foregroundStyle(Paleta.brand).frame(width: 110, alignment: .trailing)
                        Text(Money.fmt(f.gastos)).foregroundStyle(Paleta.negativo).frame(width: 110, alignment: .trailing)
                        Text(Money.fmt(f.balance)).fontWeight(.semibold).frame(width: 110, alignment: .trailing)
                    }
                    .font(.subheadline).monospacedDigit()
                    .padding(.vertical, 7)
                    if f.id != e.mensual.last?.id { Divider() }
                }
            }

            Text(L.t("Generado por Tamio", "Generated by Tamio"))
                .font(.caption2).foregroundStyle(.tertiary)
        }
        .padding(40)
        .frame(width: PDFExport.anchoCarta, alignment: .leading)
        .background(.white)
        .environment(\.colorScheme, .light)   // el PDF siempre en claro
    }

    private func filaResumen(_ label: String, _ monto: Centavos, _ color: Color, negrita: Bool = false) -> some View {
        HStack {
            Text(label).font(negrita ? .body.weight(.semibold) : .body)
            Spacer()
            Text(Money.fmt(monto))
                .font((negrita ? Font.title3 : Font.body).weight(.semibold))
                .monospacedDigit().foregroundStyle(color)
        }
        .padding(.vertical, 8)
    }
}

/// Hoja modal de "Vista previa PDF": muestra la página imprimible y permite
/// compartir/exportar el PDF real generado con ImageRenderer.
struct ReportePDFSheet: View {
    let e: EstadoFinanciero
    let periodo: String
    @Environment(\.dismiss) private var dismiss
    @State private var pdfURL: URL?

    var body: some View {
        NavigationStack {
            ScrollView([.horizontal, .vertical]) {
                ReporteHojaPDF(e: e, periodo: periodo)
                    .shadow(color: .black.opacity(0.15), radius: 12, y: 4)
                    .padding(24)
            }
            .background(Color(.systemGroupedBackground))
            .navigationTitle(L.t("Vista previa PDF", "PDF preview"))
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button(L.t("Cerrar", "Close")) { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    if let pdfURL {
                        ShareLink(item: pdfURL) {
                            Label(L.t("Compartir", "Share"), systemImage: "square.and.arrow.up")
                        }
                    }
                }
            }
        }
        .onAppear {
            pdfURL = PDFExport.render(ReporteHojaPDF(e: e, periodo: periodo),
                                      nombre: "Estado-financiero-\(periodo.replacingOccurrences(of: " ", with: "-"))")
        }
    }
}
