import SwiftUI

/// Página imprimible del "Estado financiero". Blanco y negro con verde de marca
/// solo en las cifras, según la ley de color. Es lo que se renderiza al PDF y lo
/// que se ve en la vista previa. Ancho fijo tamaño carta (lo envuelve PDFExport).
struct ReporteHojaPDF: View {
    let e: EstadoFinanciero
    let periodo: String
    /// El membrete sale de Ajustes. Antes el nombre de la iglesia estaba
    /// escrito dentro de esta vista, así que el documento no tenía forma de
    /// coincidir con lo que el tesorero había configurado.
    var iglesia: ConfiguracionIglesia = ConfiguracionIglesiaViewModel.compartido.config

    var body: some View {
        VStack(alignment: .leading, spacing: 22) {
            // Membrete
            VStack(alignment: .leading, spacing: 4) {
                Text(L.t("Estado financiero", "Financial statement"))
                    .font(.system(.title, design: .serif).weight(.bold))
                Text(periodo).font(.headline).foregroundStyle(.secondary)
                if !iglesia.membrete.isEmpty {
                    Text(iglesia.membrete).font(.subheadline).foregroundStyle(.secondary)
                }
            }

            Divider()

            // Resumen del mes
            VStack(spacing: 0) {
                filaResumen(L.t("Ingresos del mes", "Income this month"), e.ingresosMes, Paleta.brand)
                Divider()
                filaResumen(L.t("Gastos del mes", "Expenses this month"), e.gastosMes, Paleta.negativo)
                Divider()
                filaResumen(L.t("Balance neto", "Net balance"), e.balanceNeto, .primary, negrita: true)
            }
            .padding(Esp.tarjeta)
            .overlay(RoundedRectangle(cornerRadius: 12).stroke(.secondary.opacity(0.3)))

            // Tabla mensual
            Text(L.t("Resumen mensual", "Monthly summary")).font(.headline)
            VStack(spacing: 0) {
                HStack {
                    Text(L.t("MES", "MONTH")).frame(maxWidth: .infinity, alignment: .leading)
                    Text(L.t("INGRESOS", "INCOME")).frame(width: 110, alignment: .trailing)
                    Text(L.t("GASTOS", "EXPENSES")).frame(width: 110, alignment: .trailing)
                    Text(L.t("BALANCE", "BALANCE")).frame(width: 110, alignment: .trailing)
                }
                .font(.caption.weight(.semibold)).foregroundStyle(.secondary)
                .padding(.vertical, 8)
                Divider()
                ForEach(e.mensual) { f in
                    HStack {
                        Text(f.mes).frame(maxWidth: .infinity, alignment: .leading)
                        Text(Money.fmt(f.ingresos)).foregroundStyle(Paleta.brand).frame(width: 110, alignment: .trailing)
                        Text(Money.fmt(f.gastos)).foregroundStyle(Paleta.negativo).frame(width: 110, alignment: .trailing)
                        Text(Money.fmt(f.balance)).fontWeight(.semibold).frame(width: 110, alignment: .trailing)
                    }
                    .font(.subheadline).monospacedDigit()
                    .padding(.vertical, 7)
                    if f.id != e.mensual.last?.id { Divider() }
                }
            }

            FirmasPDF(iglesia: iglesia)
            PieInstitucionalPDF(iglesia: iglesia)

            Text(L.t("Generado por Tamio", "Generated by Tamio"))
                .font(.caption2).foregroundStyle(.tertiary)
        }
        .padding(Esp.hoja)
        .frame(width: PDFExport.anchoCarta, alignment: .leading)
        .background(.white)
        .environment(\.colorScheme, .light)   // el PDF siempre en claro
    }

    private func filaResumen(_ label: String, _ monto: Centavos, _ color: Color, negrita: Bool = false) -> some View {
        HStack {
            Text(label).font(negrita ? .body.weight(.semibold) : .body)
            Spacer()
            Text(Money.fmt(monto))
                .font((negrita ? Font.title3 : Font.body).weight(.semibold))
                .monospacedDigit().foregroundStyle(color)
        }
        .padding(.vertical, 8)
    }
}

/// Hoja modal de "Vista previa PDF": muestra la página imprimible y permite
/// compartir/exportar el PDF real generado con ImageRenderer.
struct ReportePDFSheet: View {
    let e: EstadoFinanciero
    let periodo: String
    @Environment(\.dismiss) private var dismiss
    @State private var pdfURL: URL?

    var body: some View {
        NavigationStack {
            // Vertical y nada más: el scroll horizontal existía para poder
            // llegar a la mitad derecha de una hoja que no cabía. Escalada,
            // cabe entera.
            ScrollView {
                HojaCartaEscalada { ReporteHojaPDF(e: e, periodo: periodo) }
                    .shadow(color: .black.opacity(0.15), radius: 12, y: 4)
                    .padding(Esp.panel)
            }
            .background(Color(.systemGroupedBackground))
            .navigationTitle(L.t("Vista previa PDF", "PDF preview"))
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button(L.t("Cerrar", "Close")) { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    if let pdfURL {
                        ShareLink(item: pdfURL) {
                            Label(L.t("Compartir", "Share"), systemImage: "square.and.arrow.up")
                        }
                    }
                }
            }
        }
        .onAppear {
            pdfURL = PDFExport.render(ReporteHojaPDF(e: e, periodo: periodo),
                                      nombre: "Estado-financiero-\(periodo.replacingOccurrences(of: " ", with: "-"))")
        }
    }
}


/// Bloque de firmas al pie de un documento. Las líneas salen de Ajustes y solo
/// se imprimen las de quien tiene nombre: una raya con un cargo debajo y nadie
/// encima no vale para nada.
struct FirmasPDF: View {
    let iglesia: ConfiguracionIglesia

    var body: some View {
        let firmantes = iglesia.firmantes
        if !firmantes.isEmpty {
            VStack(alignment: .leading, spacing: 28) {
                Divider()
                HStack(alignment: .top, spacing: 32) {
                    ForEach(Array(firmantes.enumerated()), id: \.offset) { _, f in
                        VStack(spacing: 6) {
                            // Hueco para firmar a mano sobre el papel impreso.
                            Rectangle().fill(.secondary.opacity(0.5))
                                .frame(height: 0.75)
                                .padding(.top, 34)
                            Text(f.nombre).font(.caption.weight(.semibold))
                            Text(f.cargo).font(.caption2).foregroundStyle(.secondary)
                        }
                        .frame(maxWidth: .infinity)
                    }
                }
            }
        }
    }
}

/// Pie institucional: la línea libre de Ajustes, con los datos de contacto.
struct PieInstitucionalPDF: View {
    let iglesia: ConfiguracionIglesia

    private var contacto: String {
        [iglesia.direccion, iglesia.telefono, iglesia.correo]
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
            .joined(separator: " · ")
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 3) {
            if !contacto.isEmpty {
                Text(contacto).font(.caption2).foregroundStyle(.secondary)
            }
            if !iglesia.pieInstitucional.isEmpty {
                Text(iglesia.pieInstitucional).font(.caption2).foregroundStyle(.secondary)
            }
            if !iglesia.idFiscal.isEmpty {
                Text(L.t("ID fiscal: \(iglesia.idFiscal)", "Tax ID: \(iglesia.idFiscal)"))
                    .font(.caption2).foregroundStyle(.secondary)
            }
        }
    }
}
